local SCM = select(2, ...)

SCM.DefaultSwingTimerBreakpoints = {
	{ threshold = 0, displayStyle = "decimalSeconds", precision = 1, step = 0.1, rounding = Enum.NumericRuleFormatRounding.Nearest, format = "%.1f" },
}

SCM.DefaultDB.profile.options.swingTimer = {
	combinedHeight = 40,
	MainHand = {
		enabled = true,
		hideWhileInactive = false,
		hideWhileMounted = false,
		hideWhileDead = false,
		hideWhileInVehicle = false,
		hideWhileResting = false,
		hideOutOfCombat = false,
		useCustomVisibilityCondition = false,
		customVisibilityCondition = "",
		anchorFrame = "SCM_CastBar",
		point = "BOTTOM",
		relativePoint = "TOP",
		xOffset = 0,
		yOffset = 0,
		minWidth = 200,
		matchAnchorWidth = true,
		useSmoothPowerUpdates = false,
		heightMode = "single",
		height = 20,
		width = 200,
		frameStrata = "BACKGROUND",
		frameLevel = 1,
		texture = "Solid",
		foregroundColor = { r = 0.5, g = 0.5, b = 1, a = 1 },
		backgroundTexture = "Solid",
		backgroundColor = { r = 0.2, g = 0.2, b = 0.2, a = 0.5 },
		showTicks = true,
		tickColor = { r = 0, g = 0, b = 0, a = 1 },
		tickWidth = 2,
		spark = {
			enable = false,
			color = { r = 1, g = 1, b = 1, a = 1 },
			blendMode = "ADD",
			width = 2,
			height = 22,
			xOffset = 0,
			yOffset = 0,
			useCustomTexture = false,
			texture = "Solid",
		},
		showBorder = true,
		backdropColor = { r = 0, g = 0, b = 0, a = 1 },
		backdropSize = 2,
		showValues = true,
		font = "Expressway",
		textOutline = "OUTLINE",
		showNameText = true,
		nameFontSize = 12,
		nameTextXOffset = 5,
		nameTextYOffset = 0,
		showDurationText = true,
		durationBreakpoints = CopyTable(SCM.DefaultSwingTimerBreakpoints),
		durationFontSize = 12,
		durationTextXOffset = -8,
		durationTextYOffset = 0,
	},
	OffHand = {
		enabled = true,
		hideWhileInactive = false,
		hideWhileMounted = false,
		hideWhileDead = false,
		hideWhileInVehicle = false,
		hideWhileResting = false,
		hideOutOfCombat = false,
		useCustomVisibilityCondition = false,
		customVisibilityCondition = "",
		anchorFrame = "SCM_SwingTimerMainHand,SCM_CastBar",
		point = "BOTTOM",
		relativePoint = "TOP",
		xOffset = 0,
		yOffset = 4,
		minWidth = 200,
		matchAnchorWidth = true,
		useSmoothPowerUpdates = false,
		heightMode = "single",
		height = 20,
		width = 200,
		frameStrata = "BACKGROUND",
		frameLevel = 1,
		texture = "Solid",
		foregroundColor = { r = 0.5, g = 0.5, b = 1, a = 1 },
		backgroundTexture = "Solid",
		backgroundColor = { r = 0.2, g = 0.2, b = 0.2, a = 0.5 },
		showTicks = true,
		tickColor = { r = 0, g = 0, b = 0, a = 1 },
		tickWidth = 2,
		spark = {
			enable = false,
			color = { r = 1, g = 1, b = 1, a = 1 },
			blendMode = "ADD",
			width = 2,
			height = 22,
			xOffset = 0,
			yOffset = 0,
			useCustomTexture = false,
			texture = "Solid",
		},
		showBorder = true,
		backdropColor = { r = 0, g = 0, b = 0, a = 1 },
		backdropSize = 2,
		showValues = true,
		font = "Expressway",
		textOutline = "OUTLINE",
		showNameText = true,
		nameFontSize = 12,
		nameTextXOffset = 5,
		nameTextYOffset = 0,
		showDurationText = true,
		durationBreakpoints = CopyTable(SCM.DefaultSwingTimerBreakpoints),
		durationFontSize = 12,
		durationTextXOffset = -8,
		durationTextYOffset = 0,
	},
	Ranged = {
		enabled = true,
		hideWhileInactive = false,
		hideWhileMounted = false,
		hideWhileDead = false,
		hideWhileInVehicle = false,
		hideWhileResting = false,
		hideOutOfCombat = false,
		useCustomVisibilityCondition = false,
		customVisibilityCondition = "",
		anchorFrame = "SCM_SwingTimerOffHand,SCM_SwingTimerMainHand,SCM_CastBar",
		point = "BOTTOM",
		relativePoint = "TOP",
		xOffset = 0,
		yOffset = 4,
		minWidth = 200,
		matchAnchorWidth = true,
		useSmoothPowerUpdates = false,
		heightMode = "single",
		height = 20,
		width = 200,
		frameStrata = "BACKGROUND",
		frameLevel = 1,
		texture = "Solid",
		foregroundColor = { r = 0.5, g = 0.5, b = 1, a = 1 },
		backgroundTexture = "Solid",
		backgroundColor = { r = 0.2, g = 0.2, b = 0.2, a = 0.5 },
		showTicks = true,
		tickColor = { r = 0, g = 0, b = 0, a = 1 },
		tickWidth = 2,
		spark = {
			enable = false,
			color = { r = 1, g = 1, b = 1, a = 1 },
			blendMode = "ADD",
			width = 2,
			height = 22,
			xOffset = 0,
			yOffset = 0,
			useCustomTexture = false,
			texture = "Solid",
		},
		showBorder = true,
		backdropColor = { r = 0, g = 0, b = 0, a = 1 },
		backdropSize = 2,
		showValues = true,
		font = "Expressway",
		textOutline = "OUTLINE",
		showNameText = true,
		nameFontSize = 12,
		nameTextXOffset = 5,
		nameTextYOffset = 0,
		showDurationText = true,
		durationBreakpoints = CopyTable(SCM.DefaultSwingTimerBreakpoints),
		durationFontSize = 12,
		durationTextXOffset = -8,
		durationTextYOffset = 0,
	},
}
